v0.5.0
welfare-state-analytics/riksdagen-corpus pull request #212
Opened 2022-12-20 12:14 UTC by ninpnin

2022-12-20 12:52 UTC, MansMeg commented
Great! Is it something special I should look at?

2022-12-20 12:54 UTC, MansMeg commented
Have you checked 300 random samples of these fixes: '§'-'$' and soft hyphen are correct?

2022-12-20 12:58 UTC, ninpnin commented
@MansMeg I did do that, though my count was approximate by hand. No errors were detected.

2022-12-20 13:01 UTC, ninpnin commented
@MansMeg Maybe you can briefly check formats in the corpus/metadata folder.

2022-12-20 13:14 UTC, MansMeg commented
What exactly should I look into? What has been changed?

2022-12-20 14:11 UTC, ninpnin commented
```
corpus/metadata/government.csv           |    12 +-
corpus/metadata/location_specifier.csv   |   228 +-
corpus/metadata/member_of_parliament.csv | 24934 +++++++++++++++--------------
corpus/metadata/minister.csv             |    86 +-
corpus/metadata/name.csv                 |   664 +-
corpus/metadata/party_affiliation.csv    | 19293 +++++++++++++++-------
corpus/metadata/person.csv               |   404 +-
corpus/metadata/twitter.csv              |    25 +-
8 files changed, 27659 insertions(+), 17987 deletions(-)
```

_Member of parliament_ and _party affiliation_ are structural changes, the rest is just a metadata pull from Wikidata. 

The commit that made the change can be viewed here https://github.com/welfare-state-analytics/riksdagen-corpus/pull/212/commits/a12eef67e43ea7eaa3fce43aab6745602c4c2b80 .

2022-12-20 16:14 UTC, MansMeg commented
Great! Ill look assp!

2022-12-21 12:37 UTC, ninpnin commented
#213 needs to be fixed before merging (duplicates in person.csv due to riksdagen GUIDs)

2022-12-25 08:34 UTC, MansMeg commented
I left a couple of comments. I think I found some duplicates also in the government files.

2023-01-16 12:19 UTC, ninpnin commented
Testing automatic diff sample generation:

```diff
diff --git a/corpus/protocols/1920/prot-1920--ak--59.xml b/corpus/protocols/1920/prot-1920--ak--59.xml
index a5b4e528..d9fba958 100644
--- a/corpus/protocols/1920/prot-1920--ak--59.xml
+++ b/corpus/protocols/1920/prot-1920--ak--59.xml
@@ -3135,7 +3135,7 @@
             </seg>
           </u>
           <pb facs="https://betalab.kb.se/prot-1920--ak--59/prot_1920__ak__59-039.jp2/_view"/>
-          <u xml:id="i-JAsDPJn2v8tqCMGAerBi8m" who="unknown">
+          <u xml:id="i-JAsDPJn2v8tqCMGAerBi8m" who="Q6026566" prev="i-869bf2383fd9233c-84">
             <seg xml:id="i-RuXtrURQFs75uHZvBfuNLv">
               Nr 59. = 40 Lördagen den 15 maj, e. m. Ang. ortstill- Med anledning
               härav ber jag fortfarande få yrka bifall till den Jägg $ Jill
diff --git a/corpus/protocols/1920/prot-1920--ak--8.xml b/corpus/protocols/1920/prot-1920--ak--8.xml
index 895f21f6..b91ec40f 100644
--- a/corpus/protocols/1920/prot-1920--ak--8.xml
+++ b/corpus/protocols/1920/prot-1920--ak--8.xml
@@ -991,7 +991,7 @@
             Nämnda motioner blevo på begäran bordlagda.
           </note>
           <note xml:id="i-17WWCJaMbPt2HeWZgcDWtD">
-            $ 2.
+            § 2.
           </note>
           <note xml:id="i-CMwE63UuKyRwSf9tSpjSpP">
             Till bordläggning anmäldes bankoutskottets memorial, nr 1, med
diff --git a/corpus/protocols/1922/prot-1922--ak--15.xml b/corpus/protocols/1922/prot-1922--ak--15.xml
index 64eff92a..8b0fa410 100644
--- a/corpus/protocols/1922/prot-1922--ak--15.xml
+++ b/corpus/protocols/1922/prot-1922--ak--15.xml
@@ -5723,7 +5723,7 @@
           <note type="date" xml:id="i-6CpnqgeTj8SMzQ67ja4jZB">
             Onsdagen den 8 mars. 75
           </note>
-          <u who="Q6046628" xml:id="i-d46b107a2d39fe5b-5" prev="i-d46b107a2d39fe5b-3">
+          <u who="Q5798778" xml:id="i-d46b107a2d39fe5b-5" prev="i-d46b107a2d39fe5b-3">
             <seg xml:id="i-WJXgh1HQ4N2BoMVCdVxVB4">
               Jag skall således, herr vice talman, be att få yrka bifall till
               ut- 9
diff --git a/corpus/protocols/1923/prot-1923--ak--10.xml b/corpus/protocols/1923/prot-1923--ak--10.xml
index 69a17828..f0f6a888 100644
--- a/corpus/protocols/1923/prot-1923--ak--10.xml
+++ b/corpus/protocols/1923/prot-1923--ak--10.xml
@@ -248,7 +248,7 @@
             Onsdagen den 14 februari. kl. 11 f. m.
           </note>
           <note xml:id="i-8H2gAYvw7NqVR1U3sFN8rL">
-            $1.
+            §1.
           </note>
           <note xml:id="i-TtH42fV6yKR8CaipS1QjUJ">
             Herr statsrådet Lindqvist avlämnade Kungl. Maj:ts proposition,
diff --git a/corpus/protocols/1923/prot-1923--ak--18.xml b/corpus/protocols/1923/prot-1923--ak--18.xml
index f3d3c57b..1e1178b5 100644
--- a/corpus/protocols/1923/prot-1923--ak--18.xml
+++ b/corpus/protocols/1923/prot-1923--ak--18.xml
@@ -5304,10 +5304,10 @@
             lådbrevbärarnas anställningsoch avlöningsförhållanden.
           </note>
           <note xml:id="i-3wW8WHwyFV8hEMNHnGoXKT">
-            $ 21. Justerades protokollsutdrag.
+            § 21. Justerades protokollsutdrag.
           </note>
           <note xml:id="i-BEbBLJ2V7ziZM56SigGtF2">
-            $ 22.
+            § 22.
           </note>
           <note xml:id="i-SzAQWEZBhmFhvdbruTNicH">
             Ledighet från riksdagsgöromålen beviljades:
diff --git a/corpus/protocols/1926/prot-1926--ak--9.xml b/corpus/protocols/1926/prot-1926--ak--9.xml
index 93058718..cf09b171 100644
--- a/corpus/protocols/1926/prot-1926--ak--9.xml
+++ b/corpus/protocols/1926/prot-1926--ak--9.xml
@@ -368,7 +368,7 @@
             var och en med 82 röster.
           </note>
           <note xml:id="i-84mJkVeBs3pYQc73hHaSms">
-            $ 4.
+            § 4.
           </note>
           <note xml:id="i-V2ysw9z6BQF8CUrHBN1jK3">
             Slutligen företogos val av dels tjugufyra valmän för utseende
diff --git a/corpus/protocols/1927/prot-1927--ak--15.xml b/corpus/protocols/1927/prot-1927--ak--15.xml
index a349b203..5c02cfb6 100644
--- a/corpus/protocols/1927/prot-1927--ak--15.xml
+++ b/corpus/protocols/1927/prot-1927--ak--15.xml
@@ -399,7 +399,7 @@
             Olsson i Kullenbergstorp m. fl.
           </note>
           <note xml:id="i-2r3F4g2ddVdcFdgeX9vV4k">
-            8 3. Ordet lämnades härefter på begäran till
+            § 3. Ordet lämnades härefter på begäran till
           </note>
           <note type="speaker" xml:id="i-VbdeR4fL9onZLLNr5NVbPf">
             Herr Järte, som yttrade:
diff --git a/corpus/protocols/1927/prot-1927--ak--8.xml b/corpus/protocols/1927/prot-1927--ak--8.xml
index 2a3cb218..dbf727bd 100644
--- a/corpus/protocols/1927/prot-1927--ak--8.xml
+++ b/corpus/protocols/1927/prot-1927--ak--8.xml
@@ -5893,14 +5893,14 @@
             totalisator.
           </note>
           <note xml:id="i-Ueg2ogKko3G3PYshLMH4Wg">
-            8 16. Justerades protokollsutdrag.
+            § 16. Justerades protokollsutdrag.
           </note>
           <pb facs="https://betalab.kb.se/prot-1927--ak--8/prot_1927__ak__8-063.jp2/_view"/>
           <note type="date" xml:id="i-4NnJnozDGWeHxFAJKBFvxv">
             Nr 8. 64 Onsdagen den 16 februari.
           </note>
           <note xml:id="i-TgRap9DwPs8U5xyGJNzuJ4">
-            $ 17.
+            § 17.
           </note>
           <note xml:id="i-UFpW1oNW9pzHzLbPfG31Df">
             Upplästes följande till kammaren inkomna sjukbetyg:

diff --git a/corpus/protocols/1929/prot-1929--ak--25.xml b/corpus/protocols/1929/prot-1929--ak--25.xml
index 791a8291..b56d3814 100644
--- a/corpus/protocols/1929/prot-1929--ak--25.xml
+++ b/corpus/protocols/1929/prot-1929--ak--25.xml
@@ -136,7 +136,7 @@
             till statsutskottet motionen nr 436 av herr Lövgren.
           </note>
           <note xml:id="i-8oCSCGTebsp3sC59ssry9y">
-            $ 3.
+            § 3.
           </note>
           <note xml:id="i-VENnEcoLBLVhV9pyitdGPz">
             Vidare föredrogs.herr Johanssons i Uppmälby vid kammarens nästföregående
diff --git a/corpus/protocols/1933/prot-1933--ak--3.xml b/corpus/protocols/1933/prot-1933--ak--3.xml
index 72f5a3e9..87020344 100644
--- a/corpus/protocols/1933/prot-1933--ak--3.xml
+++ b/corpus/protocols/1933/prot-1933--ak--3.xml
@@ -736,7 +736,7 @@
             Nämnda motioner bordlades.
           </note>
           <note xml:id="i-3CBqxBbP1use5EB8DoAmJV">
-            $ 24.
+            § 24.
           </note>
           <note xml:id="i-UppHLHyJBhu3Rwo4frbZeS">
             Herr talmannen meddelade, att herr Nylander nu intagit sin plats
diff --git a/corpus/protocols/1933/prot-1933--ak--38.xml b/corpus/protocols/1933/prot-1933--ak--38.xml
index 11349f15..37c49eec 100644
--- a/corpus/protocols/1933/prot-1933--ak--38.xml
+++ b/corpus/protocols/1933/prot-1933--ak--38.xml
@@ -595,21 +595,21 @@
             </seg>
           </u>
           <note xml:id="i-SAfgxpTcP1qNtB1G5tidnp">
-            $ 4.
+            § 4.
           </note>
           <note xml:id="i-4whVmtSQF3MiCcrgbxUSKA">
             Föredrogs och hänvisades till jordbruksutskottet herr Herous
             m. fl. på kammarens bord vilande motion nr 524.
           </note>
           <note xml:id="i-6p8h29xVzSnd9vMUC7D5dS">
-            $ 5.
+            § 5.
           </note>
           <note xml:id="i-Ux1usLtt7h7FpEKsQvLt3q">
             Härefter föredrogos, men bordlades åter konstitutionsutskottets
             utlåtanden nr 30 och 31 samt statsutskottets utlåtanden nr 73—78.
           </note>
           <note xml:id="i-PuU7YcXb6NKHXxypFKNhoL">
-            8 6.
+            § 6.
           </note>
           <note xml:id="i-DrVseF3x2QMaZPoNGPvJxM">
             Vid nu skedd föredragning av statsutskottets memorial, nr 79,
diff --git a/corpus/protocols/1936/prot-1936--ak--3.xml b/corpus/protocols/1936/prot-1936--ak--3.xml
index 8e24007b..6cbf1db7 100644
--- a/corpus/protocols/1936/prot-1936--ak--3.xml
+++ b/corpus/protocols/1936/prot-1936--ak--3.xml
@@ -7938,7 +7938,7 @@ [...]

2023-01-16 12:28 UTC, MansMeg commented
Nice! Are these 150 random samples of diffs? if so this is a REALLY nice way to do the quality check before merge!

2023-01-16 12:30 UTC, MansMeg commented
My only thought is how to do this with respect to the dev branch. Should we do these checks when merging to dev or when merging to main? If we do many releases from dev the problem becomes smaller. But here there are a lot of different things we fix and check. So say that page number thing is ok, but § stuff is not. Then we can merge even though we might want to merge the page number things.

What is your take?

2023-01-16 12:43 UTC, ninpnin commented
Yes. This is 150 randomly sampled diffs between the dev and main branches.

I think we should do this for each pull request. And then have each coherent 'feature' have its own pull request _featurebranch->dev_ . So if change a lot of "$"s to "§"s, that should have a pull request _dollarsign-fix-branch -> dev_.

2023-01-16 12:49 UTC, MansMeg commented
Ok. But doesnt this create a risk of extra work? We check 150 diffs for each PR? If we have checked 150 feature1 -> dev and 150 feature2 -> dev, why check 150 dev -> main if only feature1 and feature2 has been included? Or maybe in these cases we just skip the checks?

2023-01-16 13:02 UTC, ninpnin commented
Yeah that creates a little overhead. I guess we can set up Github actions so that the diff is always generated (easier), but we don't check it if the same feature has already been verified in a previous pull request.

2023-01-16 13:07 UTC, MansMeg commented
Yes. This is easy if we move to a workflow with one branch per feature fix. It will also encourage the right behaviour. 

I'm formally the reviewer. Should I review these diffs and then release v 0.5? Or is it easier for you to do it?

2023-01-16 13:13 UTC, ninpnin commented
Maybe briefly glance through them? Then we can merge.

2023-01-16 13:16 UTC, MansMeg commented
Sure! i think I would then like to actually do it to see how long it would take to do it properly. Ill fix!

2023-01-16 21:05 UTC, MansMeg commented
Ok. The first real mistake. There seems to be an error with the mapping of this person. 

I have now updated wikidata for Svensson I Malmö, but this is an error that should not happen. We should fix the bug that made this possible before merging.

```
diff --git a/corpus/protocols/1972/prot-1972--71.xml b/corpus/protocols/1972/prot-1972--71.xml
index f7c3b55f..4e5aa327 100644
--- a/corpus/protocols/1972/prot-1972--71.xml
+++ b/corpus/protocols/1972/prot-1972--71.xml
@@ -5180,7 +5180,7 @@
           <note type="speaker" xml:id="i-Eg5ZnJ5kUGaCE4TsDjcFaY">
             Herr SVENSSON i Malmö (vpk):
           </note>
-          <u who="Q6199002" xml:id="i-55fa98c671d9a021-29" next="i-55fa98c671d9a021-36">
+          <u who="unknown" xml:id="i-55fa98c671d9a021-29">
             <seg xml:id="i-CxyX4LLdx6KrzL2r19coJc">
               Herr talman! För tredje gången berör kammares debatt också anslag
               av svenska skattebetalares pengar till Världsbankens sidoorgan,
```
               
> Not correct: Should be: Q6198714

2023-01-16 21:06 UTC, MansMeg commented
Never mind! I just realized that it was correct! It was made unknown correctly!

2023-01-17 16:03 UTC, MansMeg requested changes
Hi! 

I have gone through all 150 random sampled diffs. I have added issues that have came up. I think we can merge now. The only thing left is to fix the failing unit test.

2023-01-19 17:51 UTC, MansMeg commented on corpus/metadata/location_specifier.csv
> +Q4795536,"Lekåsa, J Aron, 4:321"
Strange addition.

2023-01-19 17:59 UTC, MansMeg commented
[test: allow for duplicates in person.csv due to upstream inconsistencies]

Does this mean that we have duplicates in person an we leave that in now? I think this breaks Tomas code. We should not remove unit tests to pass the corpus.

2023-01-20 09:38 UTC, MansMeg approved these changes

2023-01-20 12:16 UTC, merged